language: ruby
cache: bundler
rvm:
  - 2.4.0
env:
  - DB=sqlite
script: 
  - bundle exec rake db:create db:migrate
  - RAILS_ENV=test bundle exec rake
bundler_args: --without production
addons:
    code_climate:
        repo_token: 7f59953bf846845cf25ebbe1a514b0f8251b7889c3e1a2ea1b8e59377b3a670f
after_success:
  - bundle exec codeclimate-test-reporter
