language: ruby
cache: bundler
rvm:
  - 2.4.0
env:
  - DB=sqlite
before_script:
  - bundle exec rake db:setup RAILS_ENV=test
script: 
  - RAILS_ENV=test bundle exec rake db:schema:load
  - RAILS_ENV=test bundle exec rake
bundler_args: --without production
