language: ruby
cache: bundler
rvm:
  - 2.5.0
env:
  - DB=sqlite
script: 
  - bundle exec rake db:create db:migrate
  - bundle exec rspec
bundler_args: --without production
addons:
    code_climate:
        repo_token: b7d334de3fdaabb7a8a6ddbd240fe65a6f04147d93d81c1eae218b5ec174544b
after_success:
  - bundle exec codeclimate-test-reporter
